set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#333333 fg=#5eacd3'

bind r {
  source-file $XDG_CONFIG_HOME/tmux/tmux.conf
  display 'config reloaded'
}

set -g base-index 1

# VIM Pane Navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind-key -r f display-popup -E "~/.local/bin/tmux-session"
bind-key n display-popup -E -w 80% -h 80% -xC -yC "zk new"
bind-key N display-popup -E -w 80% -h 80% -xC -yC "zk edit --interactive"
