[notebook]
dir = "~/Documents/notebook"

[note]
filename = "{{id}}"
id-charset = "hex"
id-length = 8
id-case = "lower"

template = "default.md"

[tool]
editor = "nvim"

[group.weekly]
paths = ["weekly"]

[group.weekly.note]
filename = "{{format-date now '%Y-W%W'}}"
template = "weekly.md"
extension = "md"

[alias]
weekly = 'zk new --no-input "$ZK_NOTEBOOK_DIR/weekly"'
